version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: carsRegistry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5444:5432"
